	<?php include 'temperaturas.php' ?>
	<ul> 
          <li><a class="tooltip" href="measuring.php?id=<? echo $id[1]; ?>&amp;municipio=<? echo $mun[1]; ?>"><span class="centrarLink">Armería <br /><span class="tempLink"><? print_r($num[1]);?> &deg;C</span></span><p>Temperatura actual: <? echo $num[1]; ?> &deg;C<br />Luminosidad actual: <? echo $lum[1]; ?> &#37;<br />Municipio: Armería<br />Estado: Colima <br />Fecha: <? echo date("d/m/Y"); ?><br /><span>Dar click al cuadro para ver más.</span></p></a></li>
          <li><a class="tooltip" href="measuring.php?id=<? echo $id[2]; ?>&amp;municipio=<? echo $mun[2]; ?>"><span class="centrarLink">Colima <br /><span class="tempLink"><? print_r($num[2]);?> &deg;C</span></span><p>Temperatura actual: <? echo $num[2]; ?> &deg;C<br />Luminosidad actual: <? echo $lum[2]; ?> &#37;<br />Municipio: Colima<br />Estado: Colima <br />Fecha: <? echo date("d/m/Y"); ?><br /><span>Dar click al cuadro para ver más.</span></p></a></li>
          <li><a class="tooltip" href="measuring.php?id=<? echo $id[3]; ?>&amp;municipio=<? echo $mun[3]; ?>"><span class="centrarLink">Comala <br /><span class="tempLink"><? print_r($num[3]);?> &deg;C</span></span><p>Temperatura actual: <? echo $num[3]; ?> &deg;C<br />Luminosidad actual: <? echo $lum[3]; ?> &#37;<br />Municipio: Comala<br />Estado: Colima <br />Fecha: <? echo date("d/m/Y"); ?><br /><span>Dar click al cuadro para ver más.</span></p></a></li>
          <li><a class="tooltip" href="measuring.php?id=<? echo $id[4]; ?>&amp;municipio=<? echo $mun[4]; ?>"><span class="centrarLink">Coquimatlán <br /><span class="tempLink"><? print_r($num[4]);?> &deg;C</span></span><p>Temperatura actual: <? echo $num[4]; ?> &deg;C<br />Luminosidad actual: <? echo $lum[4]; ?> &#37;<br />Municipio: Coquimatlán<br />Estado: Colima <br />Fecha: <? echo date("d/m/Y"); ?><br /><span>Dar click al cuadro para ver más.</span></p></a></li>
          <li><a class="tooltip" href="measuring.php?id=<? echo $id[5]; ?>&amp;municipio=<? echo $mun[5]; ?>"><span class="centrarLink">Cuahutémoc <br /><span class="tempLink"><? print_r($num[5]);?> &deg;C</span></span><p>Temperatura actual: <? echo $num[5]; ?> &deg;C<br />Luminosidad actual: <? echo $lum[5]; ?> &#37;<br />Municipio: Cuahutémoc<br />Estado: Colima <br />Fecha: <? echo date("d/m/Y"); ?><br /><span>Dar click al cuadro para ver más.</span></p></a></li>
          <li><a class="tooltip" href="measuring.php?id=<? echo $id[6]; ?>&amp;municipio=<? echo $mun[6]; ?>"><span class="centrarLink">Ixtlahucán <br /><span class="tempLink"><? print_r($num[6]);?> &deg;C</span></span><p>Temperatura actual: <? echo $num[6]; ?> &deg;C<br />Luminosidad actual: <? echo $lum[6]; ?> &#37;<br />Municipio: Ixtlahuacán<br />Estado: Colima <br />Fecha: <? echo date("d/m/Y"); ?><br /><span>Dar click al cuadro para ver más.</span></p></a></li>
          <li><a class="tooltip" href="measuring.php?id=<? echo $id[7]; ?>&amp;municipio=<? echo $mun[7]; ?>"><span class="centrarLink">Manzanillo <br /><span class="tempLink"><? print_r($num[7]);?> &deg;C</span></span><p>Temperatura actual: <? echo $num[7]; ?> &deg;C<br />Luminosidad actual: <? echo $lum[7]; ?> &#37;<br />Municipio: Manzanillo<br />Estado: Colima <br />Fecha: <? echo date("d/m/Y"); ?><br /><span>Dar click al cuadro para ver más.</span></p></a></li>
          <li><a class="tooltip" href="measuring.php?id=<? echo $id[8]; ?>&amp;municipio=<? echo $mun[8]; ?>"><span class="centrarLink">Minatitlán <br /><span class="tempLink"><? print_r($num[8]);?> &deg;C</span></span><p>Temperatura actual: <? echo $num[8]; ?> &deg;C<br />Luminosidad actual: <? echo $lum[8]; ?> &#37;<br />Municipio: Minatitlán<br />Estado: Colima <br />Fecha: <? echo date("d/m/Y"); ?><br /><span>Dar click al cuadro para ver más.</span></p></a></li>
          <li><a class="tooltip" href="measuring.php?id=<? echo $id[9]; ?>&amp;municipio=<? echo $mun[9]; ?>"><span class="centrarLink">Tecomán <br /><span class="tempLink"><? print_r($num[9]); ?> &deg;C</span></span><p>Temperatura actual: <? echo $num[9]; ?> &deg;C<br />Luminosidad actual: <? echo $lum[9]; ?> &#37;<br />Municipio: Tecomán<br />Estado: Colima <br />Fecha: <? echo date("d/m/Y"); ?><br /><span>Dar click al cuadro para ver más.</span></p></a></li>
          <li><a class="tooltip" href="measuring.php?id=<? echo $id[10]; ?>&amp;municipio=<? echo $mun[10]; ?>"><span class="centrarLinkVilla">Villa de Alvarez <br /><span class="tempLink"><? print_r($num[10]);?> &deg;C</span></span><p>Temperatura actual: <? echo $num[10]; ?> &deg;C<br />Luminosidad actual: <? echo $lum[10]; ?> &#37;<br />Municipio: Villa de Álvarez<br />Estado: Colima <br />Fecha: <? echo date("d/m/Y"); ?><br /><span>Dar click al cuadro para ver más.</span></p></a></li>    
        </ul>